

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vue_springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=false&useSSL=false
server:
  port: 9090